### ISSUE TITLE
Discord Command: Refresh Imgur authorization token

### ISSUE THREAD

**Issue by egg-meister** [Seizure/ImgurTaggingBot#2]
The application connects to Imgur using a special authorization token, known as an OAuth Token. This token expires after a period of time, and must be refreshed. The application attempts to do this automatically, but there may be situations where the token expires before its advertised expiry date. A Discord command instructing the application to refresh the token would be desirable if this occurs.

It's also worth mentioning that there seems to be a bug in the Imgur API, where the OAuth Token's expiry point is incorrectly specified, meaning tokens could well expire before expected.

**Comment by egg-meister** [comment]
I've contacted Imgur's API team about the potential bug, via their published e-mail address

**Comment by Seizure** [comment]
If a token expires early, is there a specific error returned, or some other way to detect that? Perhaps the bot could still automatically refresh the token before the expiry time based on this?

**Comment by egg-meister** [comment]
Nothing that I'm aware of. We'll have to see how much of a problem it becomes.

**Comment by egg-meister** [comment]
Manual Imgur OAuth Token refresh Discord command implemented.
Still no word from Imgur on the potential bug.
