### ISSUE TITLE
Discord command responses do not respect message character limits

### ISSUE THREAD

**Issue by Seizure** [Seizure/ImgurTaggingBot#21]
When using a command that results in content which exceeds the message limit (2000 characters) the bot spits out the following error:
Exception: Message content is too long, length must be less or equal to 2000.
Parameter name: Content

The bot should automatically split the contents into separate messages which fit.

**Comment by egg-meister** [comment]
Oops…
Hopefully now fixed!

**Comment by Seizure** [comment]
since I filed this issue, the user list has been significantly shortened. Will need to wait to test, or test with a dummy bot.

**Comment by Seizure** [comment]
closing this for now, haven't tested it yet but if it still wasn't fixed (though I am sure you did just fine) we can just re-open it
