### ISSUE TITLE
Log Imgur API bandwidth usage

### ISSUE THREAD

**Issue by egg-meister** [Seizure/ImgurTaggingBot#3]
There is a limit to how often the Imgur API can be called. If this limit is exceeded too often, the application will be blocked from Imgur. The application should output log messages at appropriate points detailing the remaining Imgur API bandwidth, and those messages should be escallated to warnings if the remaining bandwidth falls below a certain threshhold.

**Comment by egg-meister** [comment]
Somewhat complete… There's now a logger for API Bandwidth, and it is written to after each Tag command. There's probably a better place for it, though… Also, a Warning-level message should be logged upon the remaining bandwidth passing below a certain percentage, which isn't yet implemented.
As such, leaving this open

**Comment by Seizure** [comment]
The bot could easily supply a bandwidth status at the end of major Discord log items. Eg, if someone tags a submission, the bot should record this in a log channel. At the end of that log item, it could state the bandwidth status.

**Comment by egg-meister** [comment]
Implemented as of commit [78ebfbe8842b555c5a14accd49fffa3b8158c3b2](//github.com/Seizure/ImgurTaggingBot/commit/78ebfbe8842b555c5a14accd49fffa3b8158c3b2)
